// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Arthur1/economical-graphql-server-demo/ent/artist"
	"github.com/Arthur1/economical-graphql-server-demo/ent/predicate"
	"github.com/Arthur1/economical-graphql-server-demo/ent/song"
)

// SongUpdate is the builder for updating Song entities.
type SongUpdate struct {
	config
	hooks    []Hook
	mutation *SongMutation
}

// Where appends a list predicates to the SongUpdate builder.
func (su *SongUpdate) Where(ps ...predicate.Song) *SongUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetTitle sets the "title" field.
func (su *SongUpdate) SetTitle(s string) *SongUpdate {
	su.mutation.SetTitle(s)
	return su
}

// SetReleasedYear sets the "released_year" field.
func (su *SongUpdate) SetReleasedYear(i int) *SongUpdate {
	su.mutation.ResetReleasedYear()
	su.mutation.SetReleasedYear(i)
	return su
}

// AddReleasedYear adds i to the "released_year" field.
func (su *SongUpdate) AddReleasedYear(i int) *SongUpdate {
	su.mutation.AddReleasedYear(i)
	return su
}

// SetArtistID sets the "artist_id" field.
func (su *SongUpdate) SetArtistID(i int) *SongUpdate {
	su.mutation.SetArtistID(i)
	return su
}

// SetArtist sets the "artist" edge to the Artist entity.
func (su *SongUpdate) SetArtist(a *Artist) *SongUpdate {
	return su.SetArtistID(a.ID)
}

// Mutation returns the SongMutation object of the builder.
func (su *SongUpdate) Mutation() *SongMutation {
	return su.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (su *SongUpdate) ClearArtist() *SongUpdate {
	su.mutation.ClearArtist()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SongUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SongUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SongUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SongUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SongUpdate) check() error {
	if _, ok := su.mutation.ArtistID(); su.mutation.ArtistCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Song.artist"`)
	}
	return nil
}

func (su *SongUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := su.mutation.ReleasedYear(); ok {
		_spec.SetField(song.FieldReleasedYear, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedReleasedYear(); ok {
		_spec.AddField(song.FieldReleasedYear, field.TypeInt, value)
	}
	if su.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.ArtistTable,
			Columns: []string{song.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.ArtistTable,
			Columns: []string{song.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SongUpdateOne is the builder for updating a single Song entity.
type SongUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SongMutation
}

// SetTitle sets the "title" field.
func (suo *SongUpdateOne) SetTitle(s string) *SongUpdateOne {
	suo.mutation.SetTitle(s)
	return suo
}

// SetReleasedYear sets the "released_year" field.
func (suo *SongUpdateOne) SetReleasedYear(i int) *SongUpdateOne {
	suo.mutation.ResetReleasedYear()
	suo.mutation.SetReleasedYear(i)
	return suo
}

// AddReleasedYear adds i to the "released_year" field.
func (suo *SongUpdateOne) AddReleasedYear(i int) *SongUpdateOne {
	suo.mutation.AddReleasedYear(i)
	return suo
}

// SetArtistID sets the "artist_id" field.
func (suo *SongUpdateOne) SetArtistID(i int) *SongUpdateOne {
	suo.mutation.SetArtistID(i)
	return suo
}

// SetArtist sets the "artist" edge to the Artist entity.
func (suo *SongUpdateOne) SetArtist(a *Artist) *SongUpdateOne {
	return suo.SetArtistID(a.ID)
}

// Mutation returns the SongMutation object of the builder.
func (suo *SongUpdateOne) Mutation() *SongMutation {
	return suo.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (suo *SongUpdateOne) ClearArtist() *SongUpdateOne {
	suo.mutation.ClearArtist()
	return suo
}

// Where appends a list predicates to the SongUpdate builder.
func (suo *SongUpdateOne) Where(ps ...predicate.Song) *SongUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SongUpdateOne) Select(field string, fields ...string) *SongUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Song entity.
func (suo *SongUpdateOne) Save(ctx context.Context) (*Song, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SongUpdateOne) SaveX(ctx context.Context) *Song {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SongUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SongUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SongUpdateOne) check() error {
	if _, ok := suo.mutation.ArtistID(); suo.mutation.ArtistCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Song.artist"`)
	}
	return nil
}

func (suo *SongUpdateOne) sqlSave(ctx context.Context) (_node *Song, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(song.Table, song.Columns, sqlgraph.NewFieldSpec(song.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Song.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, song.FieldID)
		for _, f := range fields {
			if !song.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != song.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Title(); ok {
		_spec.SetField(song.FieldTitle, field.TypeString, value)
	}
	if value, ok := suo.mutation.ReleasedYear(); ok {
		_spec.SetField(song.FieldReleasedYear, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedReleasedYear(); ok {
		_spec.AddField(song.FieldReleasedYear, field.TypeInt, value)
	}
	if suo.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.ArtistTable,
			Columns: []string{song.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   song.ArtistTable,
			Columns: []string{song.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Song{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{song.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
