// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Song is the predicate function for song builders.
type Song func(*sql.Selector)
